[package]
name = "experiment_logging_rust_backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
journald = "0.6.0"
serde = "1.0.130"